#!/bin/bash
nvcc -Xcompiler -fPIC -c colorize.cu
nvcc -shared colorize.o -o libcolorize.so
# Create static library
ar rcs libcolorize.a colorize.o
cd call_c_test
rustc -l static=colorize -L ../ src/main.rs